{% set python_min = "3.10" %}
{% set name = "geocube" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geocube-{{ version }}.tar.gz
  sha256: 5f0f4a2143b379434d81172ae8c9fb49c2c5ff2f9723864ed79d3947a68ea37f

build:
  entry_points:
    - geocube = geocube.cli.geocube:geocube
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - appdirs
    - click >=6.0
    - geopandas >=1
    - odc-geo
    - rasterio >=1.3
    - rioxarray >=0.4
    - scipy
    - xarray >=0.17
    - pyproj >=2
    - numpy >=1.20

test:
  imports:
    - geocube
    - geocube.api
    - geocube.geo_utils
    - geocube.xarray_extensions
  commands:
    - pip check
    - geocube --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/corteva/geocube
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tool to convert geopandas vector data into rasterized xarray data

extra:
  recipe-maintainers:
    - snowman2
    - ocefpaf
