{% set name = "geocube" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geocube-{{ version }}.tar.gz
  sha256: d0deebbcd2cd169d466ef8f9e6419c8ee23914d10e00b8f7bd73f9bed468a0fb

build:
  entry_points:
    - geocube = geocube.cli.geocube:geocube
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.10
    - appdirs
    - click >=6.0
    - geopandas >=0.7
    - odc-geo
    - rasterio >=1.3
    - rioxarray >=0.4
    - scipy
    - xarray >=0.17
    - pyproj >=2
    - numpy >=1.20

test:
  imports:
    - geocube
    - geocube.api
    - geocube.geo_utils
    - geocube.xarray_extensions
  commands:
    - pip check
    - geocube --help
  requires:
    - pip

about:
  home: https://github.com/corteva/geocube
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tool to convert geopandas vector data into rasterized xarray data

extra:
  recipe-maintainers:
    - snowman2
    - ocefpaf
