{% set version = "0.4.0" %}

package:
  name: geocube
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geocube/geocube-{{ version }}.tar.gz
  sha256: b3ffeb88e3bbfbcaeaa52eb771b5173ed62ee7cadeba4dc3b1a54fc78b08d096

build:
  number: 0
  noarch: python
  entry_points:
    - geocube=geocube.cli.geocube:geocube
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - appdirs
    - click >=6.0
    - odc-geo
    - geopandas >=0.6
    - pyproj >=2
    - rasterio
    - rioxarray >=0.4.0
    - scipy
    - xarray >=0.17.0

test:
  imports:
    - geocube
    - geocube.api
    - geocube.geo_utils
    - geocube.xarray_extensions
  commands:
    - pip check
    - geocube --help
  requires:
    - pip

about:
  home: https://github.com/corteva/geocube
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tool to convert geopandas vector data into rasterized xarray data

extra:
  recipe-maintainers:
    - snowman2
    - ocefpaf
